export const SET_CURRENT_IMAGES = 'SET_CURRENT_IMAGES';
export const SET_SEARCH_BY = 'SET_SEARCH_BY';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_CATEGORY_CLICKED = 'SET_CATEGORY_CLICKED';
